apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: rest-proxy
  name: rest-proxy
spec:
  replicas: 1
  selector:
    io.kompose.service: rest-proxy
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: rest-proxy
    spec:
      containers:
        - env:
            - name: KAFKA_REST_BOOTSTRAP_SERVERS
              value: broker:29092
            - name: KAFKA_REST_HOST_NAME
              value: rest-proxy
            - name: KAFKA_REST_LISTENERS
              value: http://0.0.0.0:8082
            - name: KAFKA_REST_SCHEMA_REGISTRY_URL
              value: http://schema-registry:8081
          image: ' '
          name: rest-proxy
          ports:
            - containerPort: 8082
          resources: {}
      hostname: rest-proxy
      restartPolicy: Always
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - rest-proxy
        from:
          kind: ImageStreamTag
          name: rest-proxy:6.1.1
      type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
